name: Deploy to STAGING

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: it-incubator/ci-cd-pipelines/.github/workflows/build-and-deploy.yaml@master
    with:
      project: vercel
      environment: staging
      registry_hostname: ${{ vars.DOCKER_USERNAME }}
      argocd_server: argocd.staging.it-incubator.ru
      app_name: deploy-example
      deploy_url: https://vercel-deploy-example.staging.it-incubator.ru

      dockerfile: ./Dockerfile
      pull_request_number: ${{ github.event.issue.number }}
      comment_body: ${{ github.event.comment.body }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      run_id: ${{ github.run_id }}
      sha: ${{ github.sha }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.STG_ARGOCD_TOKEN }}

